version: '3.7'

services:
  auth:
    image: quay.io/keycloak/keycloak:23.0.1
    command:
      - start-dev  # Run Keycloak in development mode with HTTPS
      - --https-certificate-file=/opt/keycloak/certs/server.crt
      - --https-certificate-key-file=/opt/keycloak/certs/server.key
      - --import-realm  # Ensure realm is imported on first run
    ports:
      - "8443:8443"  # Keycloak over HTTPS
    environment:
      - KEYCLOAK_ADMIN=<username>
      - KEYCLOAK_ADMIN_PASSWORD=<password>
    volumes:
      - ./certs/server.crt:/opt/keycloak/certs/server.crt
      - ./certs/server.key:/opt/keycloak/certs/server.key
      - ./kc/stigman_realm.json:/opt/keycloak/data/import/stigman_realm.json
    depends_on:
      - db
    networks:
      app_network:
        aliases:
          - hostname.domain

  db:
    image: mysql:8.0
    ports:
      - "50001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=<password>
      - MYSQL_USER=<username>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=<password>
    cap_add:
      - SYS_NICE  # workaround MySQL logging bug => mbind: Operation not permitted
    volumes:
      - mysql_data:/var/lib/mysql  # Persist database data
    networks:
      - app_network

  api:
    image: nuwcdivnpt/stig-manager:latest
    environment:
      - STIGMAN_OIDC_PROVIDER=https://hostname.domain:8443/realms/stigman
      - STIGMAN_DB_HOST=<dbname>
      - STIGMAN_DB_USER=<username>
      - STIGMAN_DB_PASSWORD=<password>
      - STIGMAN_DB_PORT=3306
      - STIGMAN_CLIENT_OIDC_PROVIDER=https://hostname.domain:8443/realms/stigman
      - STIGMAN_CLIENT_WELCOME_LINK=https://link_to_help_pages
      - NODE_EXTRA_CA_CERTS=/app/certs/ca.crt
    volumes:
      - ./certs/ca/fullCA.crt:/app/certs/ca.crt
    ports:
      - "54000:54000"
    depends_on:
      - db
      - auth
    networks:
      - app_network

  nginx:
    image: nginx:1.23.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/server.crt:/etc/nginx/cert.pem
      - ./certs/server.key:/etc/nginx/privkey.pem
      - ./certs/dod/Certificates_PKCS7_v5.9_DoD.pem.pem:/etc/nginx/dod-certs.pem
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    ports:
      - "443:443"
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
