- name: Check RHEL package versions
  ignore_unreachable: yes
  hosts: reachable
  become: true
  vars_files:
    - ../../vaults/vbox_vault.yml
  vars:
    ansible_become_password: "{{ remote_host_become_pass }}"
    ansible_remote_tmp: /var/ansible_tmp
    required_packages_raw: "{{ lookup('file', playbook_dir + '/../../files/package_versions.txt').splitlines() }}"
    output_file: "{{ playbook_dir }}/../../files/rhel_vulnerability_report.txt"

  tasks:
    - name: Get primary group for local file permissions
      delegate_to: localhost
      ansible.builtin.command: id -gn {{ lookup('env', 'USER') }}
      register: primary_group
      changed_when: false

    - name: Execute Bash script fragment on remote host to check versions
      ansible.builtin.shell: |
        #!/bin/bash
        
        # --- Package Data Template (Injected by Ansible) ---
        declare -A REQUIRED_VERSIONS
        {% for line in required_packages_raw %}
        {# Filter out empty lines or comments #}
        {% if line | length > 0 and not line.startswith('#') %}
        
        {# 1. Split line into PKG_PREFIX and REQUIRED_VERSION using regex_replace #}
        {# Example input: kernel-4.18.0-555.69.1.el8_10 -> Output: kernel-4.18.0,555.69.1.el8_10 #}
        {% set split_line = line | regex_replace('^(.*)-([0-9].*)$', '\1,\2') | split(',') %}

        {% if split_line | length == 2 %}
          {% set pkg_name_prefix = split_line[0] %}
          {% set req_version = split_line[1] %}
          
          {# 2. Clean the prefix down to the base package name (e.g., kernel-4.18.0 -> kernel) #}
          {% if pkg_name_prefix is search('-[0-9]') %}
            {# Split by hyphen and take the first element #}
            {% set pkg_name_base = pkg_name_prefix.split('-') | first %}
          {% else %}
            {% set pkg_name_base = pkg_name_prefix %}
          {% endif %}
          
          REQUIRED_VERSIONS["{{ pkg_name_base | trim }}"]="{{ req_version | trim }}"
        {% endif %}
        {% endif %}
        {% endfor %}
        # ----------------------------------------------------

        REPORT_DATA=""
        HOST_NAME="{{ inventory_hostname }}"
        
        # Function to process an installed base package and all its versions
        process_package() {
            local pkg_name="$1"
            local required_ver="${REQUIRED_VERSIONS[$pkg_name]}"

            # Use rpm -qa to list ALL installed packages matching the base name
            INSTALLED_VERSIONS=$(rpm -qa "$pkg_name" --qf '%{VERSION}-%{RELEASE}\n' 2>/dev/null)
            
            if [[ -z "$INSTALLED_VERSIONS" ]]; then
                # Package not installed: Output: HOST|PACKAGE|INSTALLED_VERSION|REQUIRED_VERSION
                REPORT_DATA+="$HOST_NAME|$pkg_name|NOT_INSTALLED|$required_ver\n"
                return
            fi

            MEETS_REQUIREMENT=0
            LOWEST_DEFICIENT_INSTALLED_VER=""

            # Iterate through all installed versions
            while IFS= read -r installed_ver; do
                if [[ -z "$installed_ver" ]]; then continue; fi

                # --- Robust Version Comparison using sort -V ---
                
                FIRST_VERSION=$(echo -e "$installed_ver\n$required_ver" | sort -V | head -n 1)

                if [[ "$FIRST_VERSION" == "$installed_ver" ]] && [[ "$installed_ver" != "$required_ver" ]]; then
                    # This specific installed version is DEFICIENT.
                    
                    if [[ -z "$LOWEST_DEFICIENT_INSTALLED_VER" ]]; then
                       LOWEST_DEFICIENT_INSTALLED_VER="$installed_ver"
                    else
                        # Track the absolute lowest (oldest) version if all are deficient
                        LOWEST_CHECK=$(echo -e "$installed_ver\n$LOWEST_DEFICIENT_INSTALLED_VER" | sort -V | head -n 1)
                        if [[ "$LOWEST_CHECK" == "$installed_ver" ]]; then
                            LOWEST_DEFICIENT_INSTALLED_VER="$installed_ver"
                        fi
                    fi
                else
                    # This specific installed version MEETS or EXCEEDS the requirement.
                    MEETS_REQUIREMENT=1
                fi
            done <<< "$INSTALLED_VERSIONS"
            
            # Report failure only if no installed version met the required minimum
            if [[ "$MEETS_REQUIREMENT" -eq 0 ]] && [[ -n "$LOWEST_DEFICIENT_INSTALLED_VER" ]]; then
                REPORT_DATA+="$HOST_NAME|$pkg_name|$LOWEST_DEFICIENT_INSTALLED_VER|$required_ver\n"
            fi
        }

        # Main loop to process all required packages
        for pkg_name in "${!REQUIRED_VERSIONS[@]}"; do
            process_package "$pkg_name"
        done

        echo -e "$REPORT_DATA"
      register: package_check_results
      changed_when: false

    - name: Generate and write a single combined report
      delegate_to: localhost
      run_once: true
      ansible.builtin.copy:
        content: |
          # Package Version Deficiencies Report
          # Generated at: {{ ansible_date_time.iso8601 | regex_replace('\\..*$', '') }}
          # -------------------------------------------------------------
          # HOSTNAME,PACKAGE_NAME,INSTALLED_VERSION,REQUIRED_MINIMUM_VERSION

          {% for host in ansible_play_hosts %}
          {% set raw_stdout = hostvars[host].package_check_results.stdout | default('') %}
          {% set raw_lines = raw_stdout.split('\n') | map('trim') | reject('equalto', '') | list %}
          
          {% for line in raw_lines %}
          {% set parts = line.split('|') %}
          {% if parts | length == 4 %}
          {{ parts[0] | upper }},{{ parts[1] }},{{ parts[2] }},{{ parts[3] }}
          {% endif %}
          {% endfor %}
          {% endfor %}
        dest: "{{ output_file }}"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ primary_group.stdout }}"
        mode: '0644'