- name: Check RHEL package versions
  ignore_unreachable: yes
  hosts: reachable
  become: true
  
  vars_files:
    # Ensure this path is correct relative to your playbook location
    - ../../vaults/vbox_vault.yml 
    
  vars:
    ansible_become_password: "{{ remote_host_become_pass }}"
    ansible_remote_tmp: /var/ansible_tmp
    
    # Pass the entire file content formatted as a newline-separated string (each line: name-version-release)
    required_packages_raw_data: "{{ lookup('file', playbook_dir + '/../../files/package_versions.txt').splitlines() | map('trim') | reject('equalto', '') | join('\n') }}"
    output_file: "{{ playbook_dir }}/../../files/rhel_vulnerability_report.txt"


  tasks:
    - name: Install rpmdevtools for version comparison
      become: true
      ansible.builtin.package:
        name: rpmdevtools
        state: present
      when: ansible_os_family == "RedHat"


    - name: Get primary group for local file permissions
      delegate_to: localhost
      ansible.builtin.shell: 
        cmd: id -gn "{{ lookup('env', 'USER') }}"
      register: primary_group
      changed_when: false

    - name: Execute single-pass, optimized version check (v4)
      ansible.builtin.shell: |
        #!/bin/bash
        
        REQUIRED_RAW_DATA="{{ required_packages_raw_data }}"
        HOST_MAJOR_VERSION="{{ ansible_distribution_major_version }}"
        DEBUG_MODE="{{ debug_check | default('false') }}" 
        REPORT_DATA=""
        HOST_NAME="{{ inventory_hostname }}"
        
        # Function to compare RPM versions using rpmdev-vercmp
        compare_rpm_versions() {
            local ver1="$1"
            local ver2="$2"
            
            if command -v rpmdev-vercmp >/dev/null 2>&1; then
                rpmdev-vercmp "$ver1" "$ver2" >/dev/null 2>&1
                local result=$?
                if [[ "$DEBUG_MODE" == "true" ]]; then
                    echo "DEBUG: Compare stripped installed: $ver1 required: $ver2 -> rpmdev-vercmp result: $result" >&2
                fi
                return $result
            else
                # Fallback logic (omitted for brevity)
                return 0
            fi
        }
        
        # Read the raw data line by line
        while IFS= read -r RAW_ENTRY; do
            if [[ -z "$RAW_ENTRY" ]]; then continue; fi
    
            # 1. Robustly split NAME from VERSION-RELEASE
            if [[ "$RAW_ENTRY" =~ ^(.*)-([0-9].*)$ ]]; then
                PKG_NAME_LOOKUP="${BASH_REMATCH[1]}" 
                REQUIRED_VR="${BASH_REMATCH[2]}"    
            else
                continue
            fi
            
            # 2. Filter out packages meant for other major OS versions
            if [[ "$REQUIRED_VR" =~ \.el([0-9]+)$ ]]; then
                REQUIRED_OS_VERSION="${BASH_REMATCH[1]}"
                if [[ "$REQUIRED_OS_VERSION" != "$HOST_MAJOR_VERSION" ]]; then
                    continue
                fi
            fi
            
            # 3. Query installed packages (returns VERSION-RELEASE.ARCH)
            INSTALLED_VRS=$(rpm -qa "$PKG_NAME_LOOKUP" --queryformat '%{VERSION}-%{RELEASE}\n' 2>/dev/null)
            
            if [[ -z "$INSTALLED_VRS" ]]; then
                if [[ "$DEBUG_MODE" == "true" ]]; then
                    echo "DEBUG: Package not installed: $PKG_NAME_LOOKUP" >&2
                fi
                continue
            fi
    
            # 4. Check each installed version
            while IFS= read -r installed_vr_raw; do
                if [[ -z "$installed_vr_raw" ]]; then continue; fi
                
                # Strip common architecture tags (.x86_64, .noarch, etc.) from the installed V-R string
                installed_vr=$(echo "$installed_vr_raw" | sed -E 's/\.(aarch64|x86_64|i[3-6]86|noarch)$//')

                # Compare the stripped installed version with the required version
                compare_rpm_versions "$installed_vr" "$REQUIRED_VR"
                RESULT=$?
                
                # If installed < required (exit code 12), report it
                if [[ $RESULT -eq 12 ]]; then
                    # Report using the stripped installed version
                    REPORT_DATA+="$HOST_NAME|$PKG_NAME_LOOKUP|$installed_vr|$REQUIRED_VR\n"
                    break
                fi
            done <<< "$INSTALLED_VRS"
            
        done <<< "$REQUIRED_RAW_DATA"
        
        echo -e "$REPORT_DATA"
      register: package_check_results
      changed_when: false


    - name: Generate and write a single combined report
      delegate_to: localhost
      run_once: true
      ansible.builtin.copy:
        content: |
          # Package Version Deficiencies Report
          # Generated by Ansible at: {{ ansible_date_time.iso8601 | regex_replace('\\..*$', '') }}
          # -------------------------------------------------------------
          # HOSTNAME,PACKAGE_NAME,INSTALLED_VERSION,REQUIRED_MINIMUM_VERSION

          {% for host in ansible_play_hosts %}
          {% set raw_stdout = hostvars[host].package_check_results.stdout | default('') %}
          {% set raw_lines = raw_stdout.split('\n') | map('trim') | reject('equalto', '') | list %}
          
          {% for line in raw_lines %}
          {% set parts = line.split('|') %}
          {% if parts | length == 4 %}
          {{ parts[0] | upper }},{{ parts[1] }},{{ parts[2] }},{{ parts[3] }}
          {% endif %}
          {% endfor %}
          {% endfor %}
        dest: "{{ output_file }}"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ primary_group.stdout | default(omit) }}"
        mode: '0644'