# prepare_hosts.yml
- name: Bootstrap Ansible Directories on Hardened Hosts
  gather_facts: false
  ignore_unreachable: yes
  hosts: all
  become: yes
  vars_files:
    - ../../vaults/vbox_vault.yml
  vars:
    ansible_become_password: "{{ remote_host_become_pass }}"
    ansible_remote_tmp: "/var/ansible_tmp"

  # Added || true for idempotency
  # Explicitly ensure the top-level directory has the correct context immediately
  tasks:

    # - name: Create executable temp dirs and set context
    #   ansible.builtin.raw: >
    #     mkdir -p {{ ansible_remote_tmp }}/async &&
    #     chmod -R 1777 {{ ansible_remote_tmp }}
    #   changed_when: false
    #   ignore_errors: true # In case it's run more than once


    - name: Create executable temp dirs and set context
      ansible.builtin.raw: >
        mkdir -p {{ ansible_remote_tmp }}/async &&
        chmod -R 1777 {{ ansible_remote_tmp }} &&
       
        semanage fcontext -a -t tmp_t "{{ ansible_remote_tmp }}(/.*)?" || true && 
        restorecon -FRv {{ ansible_remote_tmp }} &&
        
        chcon -R -t tmp_t {{ ansible_remote_tmp }}
      changed_when: false
      ignore_errors: true # In case it's run more than once