- name: populate package facts
  package_facts:

# R-230253 RHEL-08-010292
- name: stigrule_230253_configure_strong_entropy
  lineinfile:
    path: /etc/sysconfig/sshd
    regexp: '^SSH_USE_STRONG_RNG='
    line: "{{ rhel8STIG_stigrule_230253_SSH_USE_STRONG_RNG_Line }}"
    create: yes
  notify: ssh_restart
  when:
    - rhel8STIG_stigrule_230253_Manage
    - "'openssh-server' in packages"

# R-230381 RHEL-08-020340
- name: stigrule_230381_display_last_logon_time
  lineinfile:
    path: /etc/pam.d/postlogin
    insertbefore: BOF
    line: "{{ rhel8STIG_stigrule_230381__etc_pam_d_postlogin_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230381_Manage

# R-230468 RHEL-08-030601
- name: stigrule_230468_enable_audit_pre_daemon_grubby
  command: "grubby --update-kernel=ALL --args=\"{{ rhel8STIG_stigrule_230468_grub_audit_args }}\""
  when: rhel8STIG_stigrule_230468_Manage
  notify: do_reboot

- name: stigrule_230468_enable_audit_pre_daemon_grub_default
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: "{{ rhel8STIG_stigrule_230468_GRUB_CMDLINE_LINUX_Line }}"
    backrefs: yes
  when: rhel8STIG_stigrule_230468_Manage
  notify: do_reboot

# R-230469 RHEL-08-030602
- name: stigrule_230469_allocate_audit_backlog_limit_grubby
  command: "grubby --update-kernel=ALL --args=\"{{ rhel8STIG_stigrule_230469_grub_audit_backlog_limit_args }}\""
  when: rhel8STIG_stigrule_230469_Manage
  notify: do_reboot

- name: stigrule_230469_allocate_audit_backlog_limit_grub_default
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: "{{ rhel8STIG_stigrule_230469_GRUB_CMDLINE_LINUX_Line }}"
    backrefs: yes
  when: rhel8STIG_stigrule_230469_Manage
  notify: do_reboot

# R-230485 RHEL-08-030741
- name: stigrule_230485_disable_chrony_server_port
  lineinfile:
    path: /etc/chrony.conf
    regexp: '^port '
    line: "{{ rhel8STIG_stigrule_230485__etc_chrony_conf_port_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230485_Manage
  notify: chronyd_restart

# R-230486 RHEL-08-030742
- name: stigrule_230486_disable_chrony_network_management
  lineinfile:
    path: /etc/chrony.conf
    regexp: '^cmdport '
    line: "{{ rhel8STIG_stigrule_230486__etc_chrony_conf_cmdport_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230486_Manage
  notify: chronyd_restart

# R-230491 RHEL-08-040004
- name: stigrule_230491_enable_kernel_page_table_isolation_grubby
  command: "grubby --update-kernel=ALL --args=\"{{ rhel8STIG_stigrule_230491_grub_pti_args }}\""
  when: rhel8STIG_stigrule_230491_Manage
  notify: do_reboot

- name: stigrule_230491_enable_kernel_page_table_isolation_grub_default
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: "{{ rhel8STIG_stigrule_230491_GRUB_CMDLINE_LINUX_Line }}"
    backrefs: yes
  when: rhel8STIG_stigrule_230491_Manage
  notify: do_reboot

# R-230494 RHEL-08-040021
- name: stigrule_230494_disable_atm_protocol_install
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230494__etc_modprobe_d_blacklist_conf_atm_install_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230494_Manage

- name: stigrule_230494_disable_atm_protocol_blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230494__etc_modprobe_d_blacklist_conf_atm_blacklist_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230494_Manage

# R-230495 RHEL-08-040022
- name: stigrule_230495_disable_can_protocol_install
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230495__etc_modprobe_d_blacklist_conf_can_install_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230495_Manage

- name: stigrule_230495_disable_can_protocol_blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230495__etc_modprobe_d_blacklist_conf_can_blacklist_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230495_Manage

# R-230496 RHEL-08-040023
- name: stigrule_230496_disable_sctp_protocol_install
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230496__etc_modprobe_d_blacklist_conf_sctp_install_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230496_Manage

- name: stigrule_230496_disable_sctp_protocol_blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230496__etc_modprobe_d_blacklist_conf_sctp_blacklist_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230496_Manage

# R-230497 RHEL-08-040024
- name: stigrule_230497_disable_tipc_protocol_install
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230497__etc_modprobe_d_blacklist_conf_tipc_install_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230497_Manage

- name: stigrule_230497_disable_tipc_protocol_blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230497__etc_modprobe_d_blacklist_conf_tipc_blacklist_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230497_Manage

# R-230498 RHEL-08-040025
- name: stigrule_230498_disable_cramfs_install
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230498__etc_modprobe_d_blacklist_conf_cramfs_install_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230498_Manage

- name: stigrule_230498_disable_cramfs_blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230498__etc_modprobe_d_blacklist_conf_cramfs_blacklist_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230498_Manage

# R-230499 RHEL-08-040026
- name: stigrule_230499_disable_firewire_install
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230499__etc_modprobe_d_blacklist_conf_firewire_install_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230499_Manage

- name: stigrule_230499_disable_firewire_blacklist
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "{{ rhel8STIG_stigrule_230499__etc_modprobe_d_blacklist_conf_firewire_blacklist_Line }}"
    create: yes
  when: rhel8STIG_stigrule_230499_Manage

# R-230551 RHEL-08-040300
- name: stigrule_230551_ensure_aide_installed
  yum:
    name: aide
    state: "{{ rhel8STIG_stigrule_230551_aide_package_state }}"
  when: rhel8STIG_stigrule_230551_Manage

- name: stigrule_230551_configure_aide_xattrs
  lineinfile:
    path: /etc/aide.conf
    regexp: '^(.*)(p\+i\+n\+u\+g\+s\+m\+S\+sha512)(\+acl)?(\+selinux)?$'
    line: '\1\2+{{ rhel8STIG_stigrule_230551_aide_xattrs_rule }}\3\4'
    backrefs: yes
    create: yes
  when:
    - rhel8STIG_stigrule_230551_Manage
    - "'aide' in packages"

# R-230552 RHEL-08-040310
- name: stigrule_230552_ensure_aide_installed
  yum:
    name: aide
    state: "{{ rhel8STIG_stigrule_230552_aide_package_state }}"
  when: rhel8STIG_stigrule_230552_Manage

- name: stigrule_230552_configure_aide_acls
  lineinfile:
    path: /etc/aide.conf
    regexp: '^(.*)(p\+i\+n\+u\+g\+s\+m\+S\+sha512)(\+xattrs)?(\+selinux)?$'
    line: '\1\2+{{ rhel8STIG_stigrule_230552_aide_acl_rule }}\3\4'
    backrefs: yes
    create: yes
  when:
    - rhel8STIG_stigrule_230552_Manage
    - "'aide' in packages"

- name: run post-remediation steps
  block:
    - name: update grub.cfg
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
      changed_when: true

    - name: update grub.cfg for UEFI systems
      command: grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == "8"
        - ansible_virtualization_type is defined and ansible_virtualization_type != "docker" # Assuming UEFI for non-docker RHEL 8
        - ansible_architecture == "x86_64"
        - "/sys/firmware/efi" in ansible_mounts | map(attribute='mount')
      changed_when: true

  # Handlers for restarting services or triggering reboots
  handlers:
    - name: ssh_restart
      service:
        name: sshd
        state: restarted
    - name: dconf_update
      command: dconf update
    - name: auditd_restart
      service:
        name: auditd
        state: restarted
    - name: chronyd_restart
      service:
        name: chronyd
        state: restarted
    - name: do_reboot
      reboot:
        reboot_timeout: 600